type files =
  | Directory of string * files array
  | File of string * string

let files =
  Directory ("bin", [|
    File ("omake.exe", {|src\main\omake.exe|});
    File ("osh.exe", {|src\main\osh.exe|})
  |])

let print_indent n =
  for _ = 1 to n do
    print_string "  "
  done

let components = ref []

let rec gen indent = function
  | Directory (name, files) ->
      print_indent indent; print_endline (Printf.sprintf {|<Directory Id="%s" Name="%s">|} name name);
      Array.iter (gen (indent + 1)) files;
      print_indent indent; print_endline (Printf.sprintf {|</Directory>|})
  | File (dst_name, src_path) ->
      components := dst_name :: !components;
      print_indent indent; print_endline (Printf.sprintf {|<Component Id="%s" Guid="*">|} dst_name);
      print_indent indent; print_endline (Printf.sprintf {|  <File Source="%s" Name="%s" KeyPath="yes"/>|} src_path dst_name);
      print_indent indent; print_endline (Printf.sprintf {|</Component>|})

let _=
  print_endline {|<?xml version="1.0"?>
<!-- THIS FILE IS GENERATED by command 'ocaml wxsgen.ml' -->
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Product Id="*" UpgradeCode="9d04204e-f404-4aeb-a6dc-84cfa09cec84" Name="OMake" Version="0.0.1" Manufacturer="OMake-dev" Language="1033">
    <Package InstallerVersion="200" Compressed="yes" Comments="Windows Installer Package"/>
    <Media Id="1" Cabinet="product.cab" EmbedCab="yes"/>
    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="ProgramFilesFolder">
        <Directory Id="OMake" Name="OMake">|};
  gen 5 files;
  print_endline
{|        </Directory>
      </Directory>
    </Directory>
    <Feature Id="DefaultFeature" Level="1">|};
  List.iter (fun s -> print_indent 3; print_endline (Printf.sprintf {|<ComponentRef Id="%s"/>|} s)) !components;
  print_endline
{|    </Feature>
  </Product>
</Wix>|}
