let _= print_string {|<?xml version="1.0"?>
<!-- THIS FILE IS GENERATED by command 'ocaml wxsgen.ml' -->
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Product Id="*" UpgradeCode="9d04204e-f404-4aeb-a6dc-84cfa09cec84" Name="OMake" Version="0.0.1" Manufacturer="OMake-dev" Language="1033">
    <Package InstallerVersion="200" Compressed="yes" Comments="Windows Installer Package"/>
    <Media Id="1" Cabinet="product.cab" EmbedCab="yes"/>
    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="ProgramFilesFolder">
        <Directory Id="INSTALLDIR" Name="OMake">
          <Directory Id="BINDIR" Name="bin">
            <Component Id="omake_exe" Guid="*">
              <File Source="src\main\omake.exe" KeyPath="yes"/>
            </Component>
            <Component Id="osh_exe" Guid="*">
              <File Source="src\main\osh.exe" KeyPath="yes"/>
            </Component>
          </Directory>
        </Directory>
      </Directory>
    </Directory>
    <Feature Id="DefaultFeature" Level="1">
      <ComponentRef Id="omake_exe"/>
      <ComponentRef Id="osh_exe"/>
    </Feature>
  </Product>
</Wix>|}
